### ISSUE TITLE
item Bone von wache: animation is weird

### ISSUE THREAD

**Issue by weiserhei** [weiserhei/showcasev3#2]
Der Item Bone, zb `item.R` ist animiert, aber stimmt nicht mit den restlichen animationen der wache überein.
Manuell erneut an `hand.R` zu parenten löst das problem, aber was ist die Ursache?

@to5ta

**Comment by to5ta** [comment]
werde mal ein neues beispiel mit n paar bones aufsetzen, da sämtliche exports etc. in blender nichts gebracht haben

edit: debug draw von allen bones einbauen

**Comment by weiserhei** [comment]
Vielleicht sind hier noch nützliche Informationen enthalten: https://github.com/mrdoob/three.js/issues/6050, lesenswert: https://github.com/mrdoob/three.js/issues/6050#issuecomment-209805668

**Comment by weiserhei** [comment]
R87dev mit ColladaLoader2 behebt das Problem, items lassen sich nun an die Bones adden und folgen der Animation.
